version: '3.8'

services:
  # Web Service Único - Todos os microserviços
  fiap-unified-service:
    build:
      context: .
      dockerfile: Dockerfile.unified
    ports:
      - "${PORT:-8000}:8000"
    environment:
      # Configurações gerais
      - PORT=${PORT:-8000}
      - ENVIRONMENT=production
      
      # MongoDB - Usar um banco unificado
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-fiap_db}
      
      # Auth Service
      - AUTH_MONGODB_COLLECTION=${AUTH_MONGODB_COLLECTION:-users}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      
      # Core Service
      - CORE_MONGODB_COLLECTION=${CORE_MONGODB_COLLECTION:-vehicles}
      
      # Sales Service
      - SALES_MONGODB_COLLECTION=${SALES_MONGODB_COLLECTION:-sales}
      
      # Customer Service
      - CUSTOMER_MONGODB_COLLECTION=${CUSTOMER_MONGODB_COLLECTION:-customers}
      
      # Redis para Rate Limiting
      - REDIS_URL=${REDIS_URL}
      
      # URLs internas (localhost para comunicação interna)
      - AUTH_SERVICE_URL=http://localhost:8000
      - CORE_SERVICE_URL=http://localhost:8000
      - SALES_SERVICE_URL=http://localhost:8000
      - CUSTOMER_SERVICE_URL=http://localhost:8000
      
      # Frontend URLs (para CORS)
      - FRONTEND_URL=${FRONTEND_URL:-https://fiap-prova-sub-fase-3.onrender.com}
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    # Otimizações para produção
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

# Configurações de rede
networks:
  default:
    driver: bridge 