services:
  # Redis para Rate Limiting
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço de Autenticação - Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data

  # Serviço de Autenticação customizado
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth-service:/app
    ports:
      - "8002:8002"
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - MONGODB_URL=${AUTH_MONGODB_URL}
      - MONGODB_DB_NAME=${AUTH_MONGODB_DB_NAME}
      - MONGODB_COLLECTION=${AUTH_MONGODB_COLLECTION}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - keycloak
      - auth-mongodb
      - redis

  # MongoDB para o serviço de autenticação
  auth-mongodb:
    image: mongo:latest
    ports:
      - "27021:27017"
    volumes:
      - auth-mongodb-data:/data/db

  # Serviço Core (Veículos)
  core-service:
    build:
      context: ./core-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./core-service:/app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${CORE_MONGODB_URL}
      - MONGODB_DB_NAME=${CORE_MONGODB_DB_NAME}
      - MONGODB_COLLECTION=${CORE_MONGODB_COLLECTION}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - core-mongodb
      - auth-service
      - redis

  # MongoDB para o core service
  core-mongodb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - core-mongodb-data:/data/db

  # Serviço de Vendas
  sales-service:
    build:
      context: ./sales-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./sales-service:/app
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=${SALES_MONGODB_URL}
      - MONGODB_DB_NAME=${SALES_MONGODB_DB_NAME}
      - MONGODB_COLLECTION=${SALES_MONGODB_COLLECTION}
      - CORE_SERVICE_URL=${CORE_SERVICE_URL}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - REDIS_URL=${REDIS_URL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    depends_on:
      - sales-mongodb
      - core-service
      - auth-service
      - redis
      - keycloak

  # MongoDB para o sales service
  sales-mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - sales-mongodb-data:/data/db

  # Serviço de Clientes
  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./customer-service:/app
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URL=${CUSTOMER_MONGODB_URL}
      - MONGODB_DB_NAME=${CUSTOMER_MONGODB_DB_NAME}
      - MONGODB_COLLECTION=${CUSTOMER_MONGODB_COLLECTION}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - customer-mongodb
      - auth-service
      - redis

  # MongoDB para o serviço de clientes
  customer-mongodb:
    image: mongo:latest
    ports:
      - "27022:27017"
    volumes:
      - customer-mongodb-data:/data/db

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_CORE_SERVICE_URL=${REACT_APP_CORE_SERVICE_URL}
      - REACT_APP_SALES_SERVICE_URL=${REACT_APP_SALES_SERVICE_URL}
      - REACT_APP_AUTH_SERVICE_URL=${REACT_APP_AUTH_SERVICE_URL}
      - REACT_APP_CUSTOMER_SERVICE_URL=${REACT_APP_CUSTOMER_SERVICE_URL}
      - REACT_APP_APP_NAME=${REACT_APP_APP_NAME}
      - REACT_APP_ENABLE_AUTH=${REACT_APP_ENABLE_AUTH}
      - REACT_APP_RETRY_ATTEMPTS=${REACT_APP_RETRY_ATTEMPTS}
      - REACT_APP_RETRY_DELAY=${REACT_APP_RETRY_DELAY}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    depends_on:
      - auth-service
      - core-service
      - sales-service
      - customer-service
    stdin_open: true
    tty: true

volumes:
  redis-data:
  keycloak-data:
  auth-mongodb-data:
  customer-mongodb-data:
  core-mongodb-data:
  sales-mongodb-data:
