services:
  # Auth Service
  - type: web
    name: auth-service
    env: python
    plan: free
    buildCommand: cd auth-service && chmod +x build.sh && ./build.sh
    startCommand: cd auth-service && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: KEYCLOAK_URL
        sync: false
      - key: KEYCLOAK_REALM
        sync: false
      - key: KEYCLOAK_CLIENT_ID
        sync: false
      - key: KEYCLOAK_CLIENT_SECRET
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MONGODB_COLLECTION
        sync: false
      - key: REDIS_URL
        sync: false

  # Customer Service
  - type: web
    name: customer-service
    env: python
    plan: free
    buildCommand: cd customer-service && chmod +x build.sh && ./build.sh
    startCommand: cd customer-service && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MONGODB_COLLECTION
        sync: false
      - key: AUTH_SERVICE_URL
        sync: false
      - key: REDIS_URL
        sync: false

  # Core Service
  - type: web
    name: core-service
    env: python
    plan: free
    buildCommand: cd core-service && pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: cd core-service && uvicorn app.adapters.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MONGODB_COLLECTION
        sync: false
      - key: AUTH_SERVICE_URL
        sync: false
      - key: REDIS_URL
        sync: false

  # Sales Service
  - type: web
    name: sales-service
    env: python
    plan: free
    buildCommand: cd sales-service && pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: cd sales-service && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MONGODB_COLLECTION
        sync: false
      - key: CORE_SERVICE_URL
        sync: false
      - key: AUTH_SERVICE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: KEYCLOAK_URL
        sync: false
      - key: KEYCLOAK_REALM
        sync: false
      - key: KEYCLOAK_CLIENT_ID
        sync: false

  # Frontend
  - type: web
    name: fiap-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_CORE_SERVICE_URL
        sync: false
      - key: REACT_APP_SALES_SERVICE_URL
        sync: false
      - key: REACT_APP_AUTH_SERVICE_URL
        sync: false
      - key: REACT_APP_CUSTOMER_SERVICE_URL
        sync: false
      - key: REACT_APP_APP_NAME
        sync: false
      - key: REACT_APP_ENABLE_AUTH
        sync: false
      - key: REACT_APP_RETRY_ATTEMPTS
        sync: false
      - key: REACT_APP_RETRY_DELAY
        sync: false
      - key: CHOKIDAR_USEPOLLING
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: fiap-mongodb
    databaseName: fiap
    plan: starter
    ipAllowList: [] 
    ipAllowList: [] 