# Configuração do Render para deploy automático
services:
  # Backend API
  - type: web
    name: fiap-backend
    env: node
    plan: free
    buildCommand: |
      cd backend && 
      npm ci --omit=dev && 
      echo "Build completed successfully"
    startCommand: |
      cd backend && 
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URL
        value: mongodb+srv://fiap:fiap123@cluster0.mongodb.net/vehicles?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://fiap-frontend.onrender.com,http://localhost:3000,https://fiap-prova-sub-fase-3-front.vercel.app

  # Frontend
  - type: web
    name: fiap-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend &&
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://fiap-backend.onrender.com
      - key: REACT_APP_API_URL
        value: https://fiap-backend.onrender.com

