services:
  # Auth Service
  - type: web
    name: auth-service
    env: docker
    plan: free
    dockerfilePath: ./auth-service/Dockerfile
    envVars:
      - key: KEYCLOAK_URL
        sync: false
      - key: KEYCLOAK_REALM
        sync: false
      - key: KEYCLOAK_CLIENT_ID
        sync: false
      - key: KEYCLOAK_CLIENT_SECRET
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MONGODB_COLLECTION
        sync: false
      - key: REDIS_URL
        sync: false

  # Customer Service
  - type: web
    name: customer-service
    env: docker
    plan: free
    dockerfilePath: ./customer-service/Dockerfile
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MONGODB_COLLECTION
        sync: false
      - key: AUTH_SERVICE_URL
        sync: false
      - key: REDIS_URL
        sync: false

  # Core Service
  - type: web
    name: core-service
    env: docker
    plan: free
    dockerfilePath: ./core-service/Dockerfile
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MONGODB_COLLECTION
        sync: false
      - key: AUTH_SERVICE_URL
        sync: false
      - key: REDIS_URL
        sync: false

  # Sales Service
  - type: web
    name: sales-service
    env: docker
    plan: free
    dockerfilePath: ./sales-service/Dockerfile
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MONGODB_COLLECTION
        sync: false
      - key: CORE_SERVICE_URL
        sync: false
      - key: AUTH_SERVICE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: KEYCLOAK_URL
        sync: false
      - key: KEYCLOAK_REALM
        sync: false
      - key: KEYCLOAK_CLIENT_ID
        sync: false

  # Frontend
  - type: web
    name: fiap-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_CORE_API_URL
        value: https://fiap-prova-sub-fase-3.onrender.com
      - key: REACT_APP_SALES_API_URL
        value: https://fiap-prova-sub-fase-3.onrender.com
      - key: REACT_APP_AUTH_API_URL
        value: https://fiap-prova-sub-fase-3.onrender.com
      - key: REACT_APP_CUSTOMER_API_URL
        value: https://fiap-prova-sub-fase-3.onrender.com
      - key: REACT_APP_API_URL
        value: https://fiap-prova-sub-fase-3.onrender.com
      - key: REACT_APP_CORE_SERVICE_URL
        value: https://fiap-prova-sub-fase-3.onrender.com
      - key: REACT_APP_SALES_SERVICE_URL
        value: https://fiap-prova-sub-fase-3.onrender.com
      - key: REACT_APP_CUSTOMER_SERVICE_URL
        value: https://fiap-prova-sub-fase-3.onrender.com
      - key: REACT_APP_APP_NAME
        value: FIAP Vehicle Sales
      - key: REACT_APP_ENABLE_AUTH
        value: true
      - key: REACT_APP_RETRY_ATTEMPTS
        value: 3
      - key: REACT_APP_RETRY_DELAY
        value: 1000
      - key: CHOKIDAR_USEPOLLING
        value: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: fiap-mongodb
    databaseName: fiap
    plan: starter
    ipAllowList: [] 